projects:
    prisma:
        schema: src/schema.graphql
    database:
        schema: prisma/prisma.yml
        extensions:
            codegen:
                src/generated/prisma-client/prisma.graphql:
                    - schema-ast
